Feature/about page
forbole/big-dipper-default-interface pull request #16
Opened 2020-10-08 08:24 UTC by YuhsinLiao1995

## Description
added about page and set the layout

## Checklist
- [v] Ran Linting
- [v] Targeted PR against correct branch.
- [v] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [v] Wrote unit tests.
- [v] Added an entry to the `CHANGELOG.md` file.
- [v] Re-reviewed `Files changed` in the Github PR explorer.

2020-10-08 09:13 UTC, ryuash requested changes
Good effort just a couple of things.

For the MaxWidth i would actually Suggest 
```
<Layout className={classes.root}>
// have a container for this page
  <div className="about-container-or-something">
  // or a diff header i forgot the sizes
    <h2 className={classes.title}>
        {t('aboutbigDipper')}
    </h2>
    <p className={classes.text}>
      {t('paragraph')}
    </p>
  </div>
</Layout>

// root css max width example
// since this only applies to desktop
{
  // in the root
  [getMinMediaQuery(theme.breakpoints.desktop)]: {
    display: 'flex',
    justifyContent: 'center';
    alignItems: 'flex-start';
  },
  // this would occur in .about-container-or-something
  [getMinMediaQuery(theme.breakpoints.desktop)]: {
    maxWidth: theme.breakpoints.maxWidth;
  },
}
```

2020-10-08 09:13 UTC, ryuash commented on src/screens/about/styles.tsx
> +      margin: '16px 16px 29px 16px',
`margin: 1rem 1rem 2rem;` <- designer request

2020-10-12 03:02 UTC, YuhsinLiao1995 commented on src/pages/_app.tsx
> +  const [isDarkMode, setMode] = useState<boolean | undefined>(true);
done

2020-10-12 13:39 UTC, ryuash approved these changes

2020-10-12 13:41 UTC, merged